#!/bin/bash
. ./patcher
function main() {
	echo "If you haven't, export those variables: MP, O, CR (if empty, automatically cored by O), CL (optional), OP (optional), SL, CIV (optional), MIL (optional)"
	echo "Checking variables..."
	set -x
	if [ -z $MP ]; then 
		exit 1
	fi
	if [ -z $O ]; then
                exit 1
        fi	
	if [ -z $SL ]; then
                exit 1
        fi
	#if [ -z $CIV ]; then
        #        exit 1
        #fi
	#if [ -z $MIL ]; then
        #        exit 1
        #fi
	if [ -z $CR ]; then
		CR=$O
	fi
	echo "OK."
	sedpatcher "manpower=0" "manpower=$MP" "$1"
	patcher "state_category = $SL" "$1"
	patcher "history = { owner = $O add_core_of = $CR" "$1"
	if [ ! -z $OP ]; then
		patcher "controller = $OP" "$1"
	fi
	if [ ! -z $CL ]; then
		patcher "add_claim_by = $CL" "$1"
	fi
	if [ ! -z $CIV ]; then
		patcher "industrial_complex = $CIV" "$1"
	fi
	if [ ! -z $MIL ]; then
		patcher "arms_factory = $MIL" "$1"
	fi
	patcher "}" "$1"
	echo "OK. Done."
	exit 0
}
main
